version: '3.9'

services:
  app:
    container_name: app
    image: workwize-api/app
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    depends_on:
      - mysql
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html/
    networks:
      - workwize-api-network

  webserver:
    container_name: webserver
    image: workwize-api/webserver
    build:
      context: ./docker/webserver
      dockerfile: Dockerfile
    depends_on:
      - app
      - mysql
    ports:
      - '${APP_PORT:-8080}:80'
    volumes:
      - ./:/var/www/html
    networks:
      - workwize-api-network

  mysql:
    container_name: mysql
    platform: linux/x86_64
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - ${FORWARD_DB_PORT:-3306}:3306
    environment:
      MYSQL_DATABASE: workwize_api
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - workwize-api-network

volumes:
  mysql:
    driver: local

networks:
  workwize-api-network:
    driver: bridge